# Generated by Django 2.2.7 on 2020-01-07 19:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandpa', '0002_auto_20200107_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 7, 19, 4, 39, 949341)),
        ),
        migrations.AlterField(
            model_name='workportfolio',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 7, 19, 4, 40, 18456)),
        ),
    ]
