# Generated by Django 2.2.7 on 2020-01-07 20:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandpa', '0004_auto_20200107_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 7, 20, 24, 24, 117872)),
        ),
        migrations.AlterField(
            model_name='workportfolio',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 7, 20, 24, 24, 190827)),
        ),
        migrations.AlterField(
            model_name='workportfolio',
            name='work_link',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
