# Generated by Django 2.2.7 on 2020-01-12 21:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandpa', '0006_auto_20200112_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 12, 21, 50, 54, 401495)),
        ),
        migrations.AlterField(
            model_name='myworkportfolio',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 12, 21, 50, 54, 477451)),
        ),
    ]
