# Generated by Django 2.2.7 on 2020-01-12 21:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandpa', '0008_auto_20200112_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 12, 21, 55, 46, 701773)),
        ),
        migrations.AlterField(
            model_name='myworkportfolio',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 12, 21, 55, 46, 770350)),
        ),
    ]
